### PR TITLE
qualify call from stats package

### PR DESCRIPTION
**Pull request by MichaelChirico**
Alternatively, we can `importFrom(stats, setNames)`.

### CODE REVIEW

**Comment by mtmorgan** [comment]
https://github.com/Bioconductor/AnnotationDbi/blob/50cba3676526d91affccae56d41ca751162305b9/NAMESPACE#L10 ? (drawn to that because the [build report](https://bioconductor.org/checkResults/devel/bioc-LATEST/AnnotationDbi/) does not report any problems related to `setNames`...) I guess the converse being (meant with curiosity) 'why do you think this is an issue'?

**Comment by MichaelChirico** [comment]
ah, forgot to check HEAD, our copy is behind. reverting.

**Comment by MichaelChirico** [comment]
thanks!!

**Comment by MichaelChirico** [comment]
FTR it was fixed here:

https://github.com/Bioconductor/AnnotationDbi/commit/f105545f297aedbdb065bb33ca6e30eb8335941e

**Pull request closed without merging**
